columns:
  longitude: float
  latitude: float
  housing_meadian_age: float
  total_rooms: float
  total_bedrooms: float
  populations: float
  households: float
  median_income: float
  median_house_value: float
  ocean_proximity: category

  target_column: median_house_value

  domain_value: 
    ocean_proximity:
      - <1H OCEAN
      - INLAND
      - ISLAND
      - NEAR BAY
      - NEAR OCEAN
